CREATE TABLE crashes_roads_combined (
    id serial primary key,
    tdg_id_ped text,
    tdg_id_veh text,
    tdg_id_roads text,
    crash_objectid integer,
    crash_report_no character varying(10),
    crash_county double precision,
    crash_route_type character varying(2),
    crash_rte_number double precision,
    crash_rte_suffix character varying(2),
    crash_inter character varying(1),
    crash_final_logm double precision,
    crash_acc_date character varying(10),
    crash_acc_day character varying(1),
    crash_acc_time character varying(8),
    crash_junction character varying(5),
    crash_acc_sev character varying(4),
    crash_doc_killed double precision,
    crash_ped_killed double precision,
    peds_inj double precision,
    crash_crash_doc_inj double precision,
    crash_weather character varying(5),
    crash_light character varying(5),
    crash_surf_cond character varying(5),
    crash_no_veh double precision,
    crash_veh_one character varying(5),
    crash_veh_two character varying(5),
    crash_coll_type character varying(5),
    crash_event_one character varying(5),
    crash_event_two character varying(5),
    crash_fix_obj character varying(5),
    crash_veh_dir_1 character varying(5),
    crash_veh_dir_2 character varying(5),
    crash_veh_move_1 character varying(5),
    crash_veh_move_2 character varying(5),
    crash_lane character varying(5),
    crash_contrib1 character varying(5),
    crash_contrib2 character varying(5),
    crash_driv_cond1 character varying(5),
    crash_driv_cond2 character varying(5),
    crash_ped_cond character varying(8),
    crash_ped_age character varying(12),
    crash_ped_move character varying(8),
    crash_ped_loc character varying(8),
    crash_signal character varying(1),
    crash_road_char character varying(5),
    crash_speed_limi character varying(2),
    crash_rd_cond character varying(5),
    crash_muni_code character varying(12),
    crash_nlf_id character varying(73),
    road_location_i character varying(12),
    road_county_id bigint,
    road_county_des character varying(30),
    road_mun_sort bigint,
    road_municipali character varying(50),
    road_id_prefix character varying(2),
    road_id_rte_no bigint,
    road_mp_suffix character varying(2),
    road_id_mp numeric,
    road_station_de character varying(150),
    road_func_class bigint,
    road_func_cla_1 character varying(100),
    road_begin_sect numeric,
    road_end_sectio numeric,
    road_road_secti character varying(100),
    road_aadt_2006 bigint,
    road_aadt_2007 bigint,
    road_aadt_2008 bigint,
    road_aadt_2009 bigint,
    road_aadt_2010 bigint,
    road_aadt_2011 bigint,
    road_aadt_2012 bigint,
    road_aadt_2013 bigint,
    road_aadt_2014 bigint,
    road_aadt bigint,
    road_aawdt_2006 bigint,
    road_aawdt_2007 bigint,
    road_aawdt_2008 bigint,
    road_aawdt_2009 bigint,
    road_aawdt_2010 bigint,
    road_aawdt_2011 bigint,
    road_aawdt_2012 bigint,
    road_aawdt_2013 bigint,
    road_aawdt_2014 bigint,
    road_aawdt bigint,
    road_single_uni numeric,
    road_combinatio numeric,
    road_routeid character varying(32),
    road_main_line bigint,
    road_roadname character varying(100),
    road_k_factor numeric,
    road_d_factor numeric,
    road_north_east numeric,
    road_south_west numeric,
    road_peak_hour_ character varying(10),
    road_motorcycle numeric,
    road_car_pickup numeric,
    road_bus numeric,
    road_small_truc numeric,
    road_large_truc numeric,
    road_num_lanes bigint,
    road_counted_fa character varying(1),
    road_length_m float
);


-- add ped crashes
INSERT INTO crashes_roads_combined (
    tdg_id_ped, tdg_id_roads, crash_objectid, crash_report_no,
    crash_county, crash_route_type, crash_rte_number, crash_rte_suffix,
    crash_inter, crash_final_logm, crash_acc_date, crash_acc_day,
    crash_acc_time, crash_junction, crash_acc_sev, crash_doc_killed,
    crash_ped_killed, peds_inj, crash_crash_doc_inj, crash_weather,
    crash_light, crash_surf_cond, crash_no_veh, crash_veh_one,
    crash_veh_two, crash_coll_type, crash_event_one, crash_event_two,
    crash_fix_obj, crash_veh_dir_1, crash_veh_dir_2, crash_veh_move_1,
    crash_veh_move_2, crash_lane, crash_contrib1, crash_contrib2,
    crash_driv_cond1, crash_driv_cond2, crash_ped_cond, crash_ped_age,
    crash_ped_move, crash_ped_loc, crash_signal, crash_road_char,
    crash_speed_limi, crash_rd_cond, crash_muni_code, crash_nlf_id,
    road_location_i, road_county_id, road_county_des, road_mun_sort,
    road_municipali, road_id_prefix, road_id_rte_no, road_mp_suffix,
    road_id_mp, road_station_de, road_func_class, road_func_cla_1,
    road_begin_sect, road_end_sectio, road_road_secti, road_aadt_2006,
    road_aadt_2007, road_aadt_2008, road_aadt_2009, road_aadt_2010,
    road_aadt_2011, road_aadt_2012, road_aadt_2013, road_aadt_2014, road_aadt,
    road_aawdt_2006, road_aawdt_2007, road_aawdt_2008, road_aawdt_2009,
    road_aawdt_2010, road_aawdt_2011, road_aawdt_2012, road_aawdt_2013,
    road_aawdt_2014, road_aawdt, road_single_uni, road_combinatio,
    road_routeid, road_main_line, road_roadname, road_k_factor, road_d_factor,
    road_north_east, road_south_west, road_peak_hour_, road_motorcycle,
    road_car_pickup, road_bus, road_small_truc, road_large_truc,
    road_num_lanes, road_counted_fa, road_length_m
)
SELECT  crashes.tdg_id, roads.tdg_id, crashes.objectid, crashes.report_no, crashes.county,
        crashes.route_type, crashes.rte_number, crashes.rte_suffix,
        crashes.inter, crashes.final_logm, crashes.acc_date, crashes.acc_day,
        crashes.acc_time, crashes.junction, crashes.acc_sev,
        crashes.doc_killed, crashes.ped_killed, crashes.doc_inj,
        crashes.peds_inj, crashes.weather, crashes.light, crashes.surf_cond,
        crashes.no_veh, crashes.veh_one, crashes.veh_two, crashes.coll_type,
        crashes.event_one, crashes.event_two, crashes.fix_obj,
        crashes.veh_dir_1, crashes.veh_dir_2, crashes.veh_move_1,
        crashes.veh_move_2, crashes.lane, crashes.contrib1, crashes.contrib2,
        crashes.driv_cond1, crashes.driv_cond2, crashes.ped_cond,
        crashes.ped_age, crashes.ped_move, crashes.ped_loc, crashes.signal,
        crashes.road_char, crashes.speed_limi, crashes.rd_cond,
        crashes.muni_code, crashes.nlf_id, roads.location_i, roads.county_id,
        roads.county_des, roads.mun_sort, roads.municipali, roads.id_prefix,
        roads.id_rte_no, roads.mp_suffix, roads.id_mp, roads.station_de,
        roads.func_class, roads.func_cla_1, roads.begin_sect, roads.end_sectio,
        roads.road_secti, roads.aadt_2006, roads.aadt_2007, roads.aadt_2008,
        roads.aadt_2009, roads.aadt_2010, roads.aadt_2011, roads.aadt_2012,
        roads.aadt_2013, roads.aadt_2014, roads.aadt, roads.aawdt_2006,
        roads.aawdt_2007, roads.aawdt_2008, roads.aawdt_2009, roads.aawdt_2010,
        roads.aawdt_2011, roads.aawdt_2012, roads.aawdt_2013, roads.aawdt_2014,
        roads.aawdt, roads.single_uni, roads.combinatio, roads.routeid,
        roads.main_line, roads.roadname, roads.k_factor, roads.d_factor,
        roads.north_east, roads.south_west, roads.peak_hour_, roads.motorcycle,
        roads.car_pickup, roads.bus, roads.small_truc, roads.large_truc,
        roads.num_lanes, roads.counted_fa, ST_Length(roads.geom)
FROM    severe_ped_crashes_2012_to_2015 crashes,
        statewide_segments roads
WHERE   crashes.geom <#> roads.geom <= 50
AND     ST_Intersects(crashes.geom,ST_Buffer(roads.geom,50));


-- add veh crashes
INSERT INTO crashes_roads_combined (
    tdg_id_veh, tdg_id_roads, crash_objectid, crash_report_no,
    crash_county, crash_route_type, crash_rte_number, crash_rte_suffix,
    crash_inter, crash_final_logm, crash_acc_date, crash_acc_day,
    crash_acc_time, crash_junction, crash_acc_sev, crash_doc_killed,
    crash_ped_killed, peds_inj, crash_crash_doc_inj, crash_weather,
    crash_light, crash_surf_cond, crash_no_veh, crash_veh_one,
    crash_veh_two, crash_coll_type, crash_event_one, crash_event_two,
    crash_fix_obj, crash_veh_dir_1, crash_veh_dir_2, crash_veh_move_1,
    crash_veh_move_2, crash_lane, crash_contrib1, crash_contrib2,
    crash_driv_cond1, crash_driv_cond2, crash_ped_cond, crash_ped_age,
    crash_ped_move, crash_ped_loc, crash_signal, crash_road_char,
    crash_speed_limi, crash_rd_cond, crash_muni_code, crash_nlf_id,
    road_location_i, road_county_id, road_county_des, road_mun_sort,
    road_municipali, road_id_prefix, road_id_rte_no, road_mp_suffix,
    road_id_mp, road_station_de, road_func_class, road_func_cla_1,
    road_begin_sect, road_end_sectio, road_road_secti, road_aadt_2006,
    road_aadt_2007, road_aadt_2008, road_aadt_2009, road_aadt_2010,
    road_aadt_2011, road_aadt_2012, road_aadt_2013, road_aadt_2014, road_aadt,
    road_aawdt_2006, road_aawdt_2007, road_aawdt_2008, road_aawdt_2009,
    road_aawdt_2010, road_aawdt_2011, road_aawdt_2012, road_aawdt_2013,
    road_aawdt_2014, road_aawdt, road_single_uni, road_combinatio,
    road_routeid, road_main_line, road_roadname, road_k_factor, road_d_factor,
    road_north_east, road_south_west, road_peak_hour_, road_motorcycle,
    road_car_pickup, road_bus, road_small_truc, road_large_truc,
    road_num_lanes, road_counted_fa, road_length_m
)
SELECT  crashes.tdg_id, roads.tdg_id, crashes.objectid, crashes.report_no,
        crashes.county, crashes.route_type, crashes.rte_number,
        crashes.rte_suffix, crashes.inter, crashes.final_logm, crashes.acc_date,
        crashes.acc_day, crashes.acc_time, crashes.junction, crashes.acc_sev, 
        crashes.doc_killed, crashes.ped_killed, crashes.doc_inj,
        crashes.peds_inj, crashes.weather, crashes.light, crashes.surf_cond,
        crashes.no_veh, crashes.veh_one, crashes.veh_two, crashes.coll_type,
        crashes.event_one, crashes.event_two, crashes.fix_obj,
        crashes.veh_dir_1, crashes.veh_dir_2, crashes.veh_move_1,
        crashes.veh_move_2, crashes.lane, crashes.contrib1, crashes.contrib2,
        crashes.driv_cond1, crashes.driv_cond2, crashes.ped_cond,
        crashes.ped_age, crashes.ped_move, crashes.ped_loc, crashes.signal,
        crashes.road_char, crashes.speed_limi, crashes.rd_cond,
        crashes.muni_code, crashes.nlf_id, roads.location_i, roads.county_id,
        roads.county_des, roads.mun_sort, roads.municipali, roads.id_prefix,
        roads.id_rte_no, roads.mp_suffix, roads.id_mp, roads.station_de,
        roads.func_class, roads.func_cla_1, roads.begin_sect, roads.end_sectio,
        roads.road_secti, roads.aadt_2006, roads.aadt_2007, roads.aadt_2008,
        roads.aadt_2009, roads.aadt_2010, roads.aadt_2011, roads.aadt_2012,
        roads.aadt_2013, roads.aadt_2014, roads.aadt, roads.aawdt_2006,
        roads.aawdt_2007, roads.aawdt_2008, roads.aawdt_2009, roads.aawdt_2010,
        roads.aawdt_2011, roads.aawdt_2012, roads.aawdt_2013, roads.aawdt_2014,
        roads.aawdt, roads.single_uni, roads.combinatio, roads.routeid,
        roads.main_line, roads.roadname, roads.k_factor, roads.d_factor,
        roads.north_east, roads.south_west, roads.peak_hour_, roads.motorcycle,
        roads.car_pickup, roads.bus, roads.small_truc, roads.large_truc,
        roads.num_lanes, roads.counted_fa, ST_Length(roads.geom)
FROM    severe_veh_crashes_2012_to_2015 crashes,
        statewide_segments roads
WHERE   crashes.geom <#> roads.geom <= 50
AND     ST_Intersects(crashes.geom,ST_Buffer(roads.geom,50));
